server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guodongchang-github/configRepository
          username: github用户名
          password: github密码